# Generated by Django 4.2.7 on 2023-11-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(default='default_username', max_length=150, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('player_id', models.IntegerField()),
            ],
        ),
    ]
