# Generated by Django 4.2.7 on 2023-11-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
